In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])

In [3]:
a[1]

20

In [6]:
a = np.array([[10 , 20],[30, 40], [50, 60]])
a.ndim

2

In [8]:
a.itemsize

4

In [9]:
a.dtype

dtype('int32')

In [11]:
a = np.array([[10 , 20],[30, 40], [50, 60]], dtype=np.float64)
a.itemsize

8

In [12]:
a

array([[10., 20.],
       [30., 40.],
       [50., 60.]])

In [13]:
a.size

6

In [14]:
a.shape

(3, 2)

In [16]:
a = np.array([[10 , 20],[30, 40], [50, 60]], dtype=complex)
a

array([[10.+0.j, 20.+0.j],
       [30.+0.j, 40.+0.j],
       [50.+0.j, 60.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
l = range(5)
l

range(0, 5)

In [20]:
l[2]

2

In [21]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [22]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [24]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [27]:
a = np.array([[10 , 20],[30, 40], [50, 60]])
a.shape

(3, 2)

In [29]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [28]:
a.reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
a.reshape(6, 1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [31]:
a.ravel()

array([10, 20, 30, 40, 50, 60])

In [32]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [33]:
a = np.array([[10 , 20],[30, 40], [50, 60]])

In [35]:
a.min()

10

In [36]:
a.max()

60

In [37]:
a.sum()

210

In [38]:
a.sum(axis=0)

array([ 90, 120])

In [39]:
a.sum(axis=1)

array([ 30,  70, 110])

In [40]:
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532],
       [7.07106781, 7.74596669]])

In [41]:
np.std(a)

17.07825127659933

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2,]])