In [1]:
import numpy as np

In [2]:
n = [6, 7, 8]

In [3]:
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [5]:
a = np.array([10, 20, 30, 40])

In [6]:
a[0:2]

array([10, 20])

In [7]:
a[-1]

40

In [11]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

In [13]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
a[1,2]

60

In [9]:
a[0:2, 2]

array([30, 60])

In [14]:
a[-1]

array([70, 80, 90])

In [16]:
a[-1, 0:2]

array([70, 80])

In [17]:
a[:,1:3]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [18]:
for row in a:
    print(row)

[10 20 30]
[40 50 60]
[70 80 90]


In [19]:
for cell in a.flat:
    print(cell)

10
20
30
40
50
60
70
80
90


In [21]:
a = np.arange(6).reshape(3,2)
b = np.arange(6, 12).reshape(3,2)

In [22]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [27]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [29]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [32]:
result = np.hsplit(a, 3)

In [33]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [34]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [35]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [37]:
result = np.vsplit(a, 2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [38]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])